---
title: "Project_CovidData"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#loading the required libraries
library(dplyr)
library(tools)
library(tidyverse)
library(httr)
```


```{r}
#adding column 'Active' to the dataframe if it is not present
add_active_col_if_not_present <- function(df) {
  if ("Active" %in% colnames(df)) {
    return(df)
  }
  else {
    df$Active <- df$Confirmed - df$Deaths - df$Recovered
    df$Active <- as.integer(df$Active)
    return(df)
  }
}
```


```{r}
#changing the column name from 'Country.Region' to 'Country_Region'
change_colname <- function(df) {
  if ("Country.Region" %in% colnames(df)) {
    colnames(df)[which(names(df) == "Country.Region")] <- "Country_Region" 
  }
  return(df)
}
```


```{r}
#cleaning the data
#using the above functions to create it into a structured format
#selecting the desired columns from the dataframe
#grouping by country and summarizing the values of the rest of the columns
#changing all NA's to 0
#extracting the date and using it for a new column 'Date'
data_clean_from_url <- function(dir_name, filename) {
  filepath <- paste(dir_name, filename, sep="/")
  covid_file <- read.csv(url(filepath))
  covid_file <- add_active_col_if_not_present(covid_file)
  covid_file <- change_colname(covid_file)
  covid_file <- covid_file %>% dplyr::select(Country_Region, Confirmed, Deaths, Recovered, Active)
  covid_file <- covid_file %>% group_by(Country_Region) %>% summarize_all(sum)
  #making all NAs enteries to 0
  covid_file[is.na(covid_file)] <- 0
  #extracting date from the filename
  file_date <- gsub("^.*/", "", filename)
  #mutating the same in the new column Date
  covid_file$Date <- file_date
  #changing the data type of the column 'Date'
  covid_file$Date <- as.Date(covid_file$Date, "%m-%d-%Y")
  return(covid_file)
}
```


```{r}
#getting csv files for each day from github
get_filename_from_github <- function(github_url_api_link, github_folder) {
  req <- GET(github_url_api_link)
  stop_for_status(req)
  file_list <- unlist(lapply(content(req)$tree, "[", "path"), use.names = F)
  csv_list <- grep(github_folder, file_list, value = TRUE, fixed = TRUE)
  return(csv_list)
}

csv_list <- get_filename_from_github("https://api.github.com/repos/chetnakhanna16/COVID-19/git/trees/master?recursive=1", "csse_covid_19_data/csse_covid_19_daily_reports/")
```

```{r}
#creating an empty data frame 
final_df <- data.frame(Country_Region=factor(), Confirmed=integer(), Deaths=integer(), Recovered=integer(), Active=integer())

#writing separate file names from the list
filenames <- strsplit(csv_list, "\n")

#processing one csv file at a time from our path
for (filename in filenames) {
  #using only the csv files
  if (str_detect(filename, ".csv")){
    #cleaning the data
    df_covid <- data_clean_from_url("https://raw.githubusercontent.com/chetnakhanna16/COVID-19/master", filename)
    #creating the final dataframe
    final_df <- rbind(df_covid, final_df)
  }
}

#changing the column name 'Country_Region' to 'Country'
colnames(final_df)[which(names(final_df) == "Country_Region")] <- "Country" 

#printing the final dataframe with updated COVID-19 data 
final_df
```

```{r}
#save dataframe in a csv
save_df_to_csv <- function(df) {
  write.csv(x=df, file="./Covid19.csv", row.names=FALSE)
}

save_df_to_csv(final_df)
```

